1	1	Transport and catabolism
2	1	Cellular community
3	1	Cell motility
4	1	Cell growth and death
5	2	Chronology: Nervous system agents
6	2	Target-based classification: G protein-coupled receptors
7	2	Target-based classification: Nuclear receptors
8	2	Target-based classification: Enzymes
9	2	Target-based classification: Ion channels
10	2	Skeleton-based classification
11	2	Chronology: Antiinfectives
12	2	Target-based classification: Transporters
13	2	Structure-based classification
14	2	Chronology: Other drugs
15	2	Chronology: Antineoplastics
16	3	Cancers: Specific types
17	3	Drug resistance
18	3	Infectious diseases: Bacterial
19	3	Substance dependence
20	3	Cardiovascular diseases
21	3	Infectious diseases: Viral
22	3	Neurodegenerative diseases
23	3	Cancers: Overview
24	3	Immune diseases
25	3	Infectious diseases: Parasitic
26	3	Endocrine and metabolic diseases
27	4	Transcription
28	4	Translation
29	4	Replication and repair
30	4	Folding, sorting and degradation
31	5	Signal transduction
32	5	Membrane transport
33	5	Signaling molecules and interaction
34	6	Development
35	6	Digestive system
36	6	Endocrine system
37	6	Excretory system
38	6	Environmental adaptation
39	6	Sensory system
40	6	Immune system
41	6	Nervous system
42	6	Circulatory system
43	7	Nucleotide metabolism
44	7	Metabolism of terpenoids and polyketides
45	7	Glycan biosynthesis and metabolism
46	7	Lipid metabolism
47	7	Energy metabolism
48	7	Metabolism of other amino acids
49	7	Metabolism of cofactors and vitamins
50	7	Xenobiotics biodegradation and metabolism
51	7	Amino acid metabolism
52	7	Chemical structure transformation maps
53	7	Global and overview maps
54	7	Biosynthesis of other secondary metabolites
55	7	Carbohydrate metabolism
